---
title: "hw1_jack"
author: "Jack, Sharon"
date: "1/13/2022"
output:
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
cars=read.csv("mtcars.csv")
head(cars)
```
## Q1

```{r}
v1 = mean(cars$mpg)
v2 = mean(cars$cyl)
v3 = mean(cars$disp)
v4 = mean(cars$hp)
v5 = mean(cars$drat)
v6 = mean(cars$wt)
v7 = mean(cars$qsec)
v8 = mean(cars$vs)
v9 = mean(cars$am)
v10 = mean(cars$gear)
v11 = mean(cars$carb)
tab <- matrix(c(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11), ncol=11)
colnames(tab) <- c("mpg", "cyl", "disp", "hp", "drat", "wt", "qsec", "vs", "am", "gear", "carb")
rownames(tab) <- c("mean")
tab
```

## Q2

```{r}
df = as.data.frame(cars)
df <- df[ , -which(names(df) %in% c("model"))]
result = cov(df)
result
```

## Q5

```{r}
cars_num=subset(cars,select=-c(model))
pairs(cars_num, pch=20)
```
## Q7

```{r}
library(fmsb)
max_min <- data.frame(mpg = c(6, 0), cyl = c(6, 0), disp = c(6, 0), hp = c(6, 0), drat = c(6, 0), wt = c(6, 0), qsec = c(6, 0), vs = c(6, 0), am = c(6, 0), gear = c(6, 0), carb = c(6, 0))
rownames(max_min) <- c("max", "min")
df=data.frame(cars_num)
df <- log(df[ , -which(names(df) %in% c("am","vs"))])
df$vs <- cars_num$vs
df$am <- cars_num$am
df <- rbind(max_min, df)
df
radarchart(df)
```
