---
title: "hw3alex&jack"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Q1.1

```{r}
data = read.delim("multiple.txt", sep = " ",header=FALSE)
```

```{r cars}
sample_mean = colMeans(data)
sample_sd = sapply(data, sd)
hnull = hnull = integer(50)

n = nrow(data)
t_statistic = (sample_mean - hnull)/(sample_sd/sqrt(n))

pval = 2*apply(rbind(pt(t_statistic, df = n-1, lower.tail = F),
                     pt(t_statistic, df = n-1, lower.tail = T)), 2, min)
rejection_p <- pval < 0.1
print(pval)
print(rejection_p)

```

## Q1.2

```{r}
alpha = 0.1
FWER = 1 - (1 - alpha)^50
R = sum(rejection_p)
V = sum(rejection_p[11:50])
print(FWER)
print(V/R)
```
FWER: 0.9948462
FDP: 0.2857143

## Q1.3

```{r}
pval.bon = p.adjust(pval, method = "bonferroni")
rejection_bon = pval.bon < 0.1
print(rejection_bon)
FWER.bon = 1 - (1 - alpha/50)^50
print(FWER.bon)
```

FWER: 0.09525318

## Q1.4

```{r}
pval.bh = p.adjust(pval, method = "BH")
rejection_bh = pval.bh < 0.1
alphas = 0.1 * seq(1/50, 1, by = 1/50)
FWER.bh = 1 - prod(1 - alphas)
FDP_bh = sum(rejection_bh[11:50])/sum(rejection_bh)
print(FWER.bh)
print(FDP_bh)
```

BH's FWER is slightly lower than step1 and way higher than step2 but BH's FDP is 0, which is way lower than step1 and 3.





